# Generated by Django 5.0.6 on 2024-06-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_post_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
