# Generated by Django 5.0.6 on 2024-06-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
