# Generated by Django 5.0.6 on 2024-06-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfos', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='greeting',
            field=models.CharField(default='', max_length=128, verbose_name='인삿말'),
        ),
    ]
