# Generated by Django 5.0.6 on 2024-06-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='책제목')),
                ('writer', models.CharField(max_length=128, verbose_name='저자')),
                ('publisher', models.CharField(max_length=128, verbose_name='출판사')),
                ('link', models.CharField(max_length=128, verbose_name='구매링크')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
