# Generated by Django 5.0.6 on 2024-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfos', '0003_post_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='greeting',
            field=models.CharField(max_length=128, verbose_name='인삿말'),
        ),
    ]
