# Generated by Django 5.0.6 on 2024-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfos', '0005_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bookinfos_photo', verbose_name='책표지'),
        ),
    ]
