# Generated by Django 5.0.6 on 2024-06-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withmusic', '0003_rename_writer_music_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='author',
            new_name='writer',
        ),
    ]
